/**
 * Clans, with a door and someone holding it.
 *
 * ## Membership still lives on the profile
 *
 * A clan's total is the sum of its members' Face, and membership is a tag
 * written on a profile. That has not changed and it is what keeps a clan from
 * ever disagreeing with its own members: the table is folded out of the
 * profiles on demand, so there is nothing separate to drift.
 *
 * What is new is a small record beside it holding the one thing membership
 * cannot express: who owns the tag, and who has asked to get in. Claiming an
 * unclaimed tag makes you its owner. After that, joining is a request, and the
 * owner decides.
 *
 * ## What that guard is and is not worth
 *
 * A pilot id is a device identifier that can be regenerated by clearing site
 * data, so this is not a security boundary and it is not sold as one. Somebody
 * determined to get into a clan they were refused from can make a new identity
 * and ask again with a different name, and their Face starts at zero when they
 * do.
 *
 * It is worth having anyway, because that is not the problem it solves. The
 * problem is that a clan with an open door is not a group, it is a hashtag: you
 * cannot run one, you cannot say who is in it, and a tag somebody built up can
 * be walked into by anyone who read it off the board. Approval makes a clan a
 * thing you are let into, which is the entire point of having clans.
 *
 * ## Ownership has to survive the owner leaving
 *
 * If the owner walks, the clan passes to whoever has been in it longest rather
 * than dissolving. A clan that evaporates when one person quits would take
 * everyone else's pooled Face with it, and none of them did anything.
 */

import * as profiles from './profiles';

export const TAG_PATTERN = /^[A-Z0-9]{2,4}$/;

/** The bit of a clan that cannot be derived: who runs it, and who is knocking. */
export interface ClanRecord {
  tag: string;
  ownerId: string;
  createdAt: number;
  /** Pilots who have asked to join and are waiting on the owner. */
  pending: Array<{ id: string; name: string; askedAt: number }>;
}

const records = new Map<string, ClanRecord>();

/** How many requests one clan will hold. Past this the owner has stopped caring. */
const MAX_PENDING = 40;

export interface ClanRow {
  tag: string;
  /** Sum of every member's lifetime Face. */
  face: number;
  members: number;
  /** The highest single run anyone in the clan has posted. */
  bestScore: number;
  /** Whoever is carrying the clan, for a line the board can actually name. */
  topPilot: string | null;
  topPilotAvatar: string | null;
}

/**
 * Fold a tag off the wire into the one shape we store, or refuse it.
 *
 * Whitespace and case are corrected rather than rejected, because "  face " and
 * "Face" are both a person typing FACE and refusing them teaches nothing.
 * Anything still wrong after that is genuinely wrong.
 */
export function normaliseTag(raw: unknown): string | null {
  if (typeof raw !== 'string') return null;
  const tag = raw.trim().toUpperCase();
  return TAG_PATTERN.test(tag) ? tag : null;
}

/** Every clan that has at least one member, best first. */
export function table(limit: number): ClanRow[] {
  const rows = new Map<string, ClanRow>();
  // The leader's own total, kept beside the row rather than on it. ClanRow is
  // the public shape and a scratch field would go out on every response.
  const leaderFace = new Map<string, number>();

  for (const profile of profiles.all()) {
    const tag = profile.clanTag;
    if (!tag) continue;

    const row = rows.get(tag) ?? {
      tag,
      face: 0,
      members: 0,
      bestScore: 0,
      topPilot: null,
      topPilotAvatar: null,
    };

    row.face += Math.max(0, profile.lifetimeFace);
    row.members += 1;
    row.bestScore = Math.max(row.bestScore, Math.max(0, profile.bestScore));

    // The top pilot is decided on lifetime Face, the same number the clan is
    // ranked on, so the name shown is the reason the clan is where it is.
    if (profile.lifetimeFace > (leaderFace.get(tag) ?? -1)) {
      leaderFace.set(tag, profile.lifetimeFace);
      row.topPilot = profile.name;
      row.topPilotAvatar = profile.avatarUrl;
    }

    rows.set(tag, row);
  }

  return [...rows.values()]
    .sort((a, b) => b.face - a.face || a.tag.localeCompare(b.tag))
    .slice(0, Math.max(0, limit));
}

export interface ClanDetail extends ClanRow {
  roster: Array<{
    id: string;
    name: string;
    avatarUrl: string | null;
    lifetimeFace: number;
    runs: number;
  }>;
  /** Where this clan sits on the table, 1-based. Zero when it has no members. */
  place: number;
  ownerId: string | null;
  ownerName: string | null;
  pending: Array<{ id: string; name: string; askedAt: number }>;
}

export function detail(tag: string): ClanDetail | null {
  const all = table(Number.MAX_SAFE_INTEGER);
  const index = all.findIndex((row) => row.tag === tag);
  const record = records.get(tag);

  // A tag with a record but no members yet is still a real clan: its owner
  // claimed it and has not posted a run. Returning null would make it look
  // unclaimed and let the next person take it.
  if (index < 0 && !record) return null;

  const row: ClanRow = all[index] ?? {
    tag,
    face: 0,
    members: 0,
    bestScore: 0,
    topPilot: null,
    topPilotAvatar: null,
  };

  return {
    ...row,
    place: index < 0 ? 0 : index + 1,
    ownerId: record?.ownerId ?? null,
    ownerName: record ? (profiles.get(record.ownerId)?.name ?? null) : null,
    pending: record?.pending ?? [],
    roster: profiles
      .membersOf(tag)
      .sort((a, b) => b.lifetimeFace - a.lifetimeFace || a.firstSeen - b.firstSeen)
      .slice(0, 50)
      .map((p) => ({
        id: p.id,
        name: p.name,
        avatarUrl: p.avatarUrl,
        lifetimeFace: p.lifetimeFace,
        runs: p.runs,
      })),
  };
}

export type JoinOutcome =
  /** The tag was unclaimed, so they took it and now own it. */
  | { status: 'founded'; tag: string }
  /** Already a member. Nothing happened, and saying so is not an error. */
  | { status: 'member'; tag: string }
  /** Asked to join. Waiting on the owner. */
  | { status: 'requested'; tag: string; ownerName: string | null }
  | { status: 'left' }
  | { status: 'refused'; reason: string };

/**
 * Ask to join a clan, found one, or leave the one you are in.
 *
 * `ensure` rather than `get` on the profile, because joining is a perfectly
 * reasonable first thing to do: somebody opens an invite link before they have
 * ever finished a run, and refusing them until they post a score would make the
 * invite look broken to exactly the person it was meant to bring in.
 */
export function join(id: string, name: string, tag: string | null, now: number): JoinOutcome {
  profiles.ensure(id, name);

  if (tag === null) {
    leave(id);
    return { status: 'left' };
  }

  const profile = profiles.get(id);
  if (profile?.clanTag === tag) return { status: 'member', tag };

  const record = records.get(tag);

  // Nobody has this tag. Taking it makes you its owner, and membership is
  // immediate because there is no one to ask.
  if (!record) {
    leave(id);
    records.set(tag, { tag, ownerId: id, createdAt: now, pending: [] });
    profiles.setClan(id, tag);
    persist();
    return { status: 'founded', tag };
  }

  if (record.pending.some((p) => p.id === id)) {
    return { status: 'requested', tag, ownerName: profiles.get(record.ownerId)?.name ?? null };
  }

  if (record.pending.length >= MAX_PENDING) {
    return { status: 'refused', reason: 'That clan has too many requests waiting.' };
  }

  record.pending.push({ id, name, askedAt: now });
  persist();
  return { status: 'requested', tag, ownerName: profiles.get(record.ownerId)?.name ?? null };
}

/** Every request a pilot has out, so the client can show "waiting" anywhere. */
export function pendingFor(id: string): string[] {
  const out: string[] = [];
  for (const record of records.values()) {
    if (record.pending.some((p) => p.id === id)) out.push(record.tag);
  }
  return out;
}

export type DecideOutcome =
  | { ok: true; tag: string; memberId: string }
  | { ok: false; code: number; reason: string };

/** The owner lets someone in, or turns them away. Only the owner may. */
export function decide(
  tag: string,
  ownerId: string,
  memberId: string,
  approve: boolean,
): DecideOutcome {
  const record = records.get(tag);
  if (!record) return { ok: false, code: 404, reason: 'No such clan.' };
  if (record.ownerId !== ownerId) {
    return { ok: false, code: 403, reason: 'Only the clan owner can do that.' };
  }

  const index = record.pending.findIndex((p) => p.id === memberId);
  if (index < 0) return { ok: false, code: 404, reason: 'No request from that pilot.' };

  const request = record.pending[index];
  record.pending.splice(index, 1);

  if (approve && request) {
    // Out of whatever they were in first, so a pilot is never in two clans and
    // their Face never counts twice on the table.
    leave(request.id);
    profiles.ensure(request.id, request.name);
    profiles.setClan(request.id, tag);
  }

  persist();
  return { ok: true, tag, memberId };
}

/**
 * Take a pilot out of whatever clan they are in, and hand on the keys if they
 * were holding them.
 *
 * A clan does not dissolve when its owner quits. Everyone else's pooled Face is
 * in it and none of them did anything, so ownership passes to whoever has been
 * around longest. Only a clan with nobody left in it is removed.
 */
export function leave(id: string): void {
  const profile = profiles.get(id);
  const tag = profile?.clanTag ?? null;

  // Drop any outstanding requests too. Leaving means leaving.
  for (const record of records.values()) {
    const index = record.pending.findIndex((p) => p.id === id);
    if (index >= 0) record.pending.splice(index, 1);
  }

  if (!tag) {
    persist();
    return;
  }

  profiles.setClan(id, null);

  const record = records.get(tag);
  if (!record || record.ownerId !== id) {
    persist();
    return;
  }

  const heir = profiles
    .membersOf(tag)
    .filter((p) => p.id !== id)
    .sort((a, b) => a.firstSeen - b.firstSeen)[0];

  if (heir) record.ownerId = heir.id;
  else records.delete(tag);

  persist();
}

// Persistence -------------------------------------------------------------

export function serialise(): unknown {
  return [...records.values()];
}

export function restore(raw: unknown): void {
  if (!Array.isArray(raw)) return;
  records.clear();

  for (const item of raw as ClanRecord[]) {
    const tag = normaliseTag(item?.tag);
    if (!tag || typeof item.ownerId !== 'string') continue;
    records.set(tag, {
      tag,
      ownerId: item.ownerId,
      createdAt: typeof item.createdAt === 'number' ? item.createdAt : 0,
      pending: Array.isArray(item.pending) ? item.pending : [],
    });
  }
}

let persist: () => void = () => {};

export function onChange(handler: () => void): void {
  persist = handler;
}
